version: '3.8'

services:
  app:
    build: .
    image: node-mysql-app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./node_modules:/node_modules
      - ./:/app
    stdin_open: true
    tty: true
